services:
  signaling_server:
    build:
      context: .
      dockerfile: Dockerfile
      target: signaling_server_build
    ports:
      - "3000:3000"
    environment:
      - MEDIASOUP_WORKER_URL=ws://mediasoup_worker:4000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mediasoup_worker
      - turn_server
      - redis
    restart: always

  mediasoup_worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: mediasoup_worker_build
    ports:
      - "4000:4000"
      - "40000-40010:40000-40010/udp"
    environment:
      - MEDIASOUP_ANNOUNCED_IP=127.0.0.1
      - TURN_SERVER_URL=turn_server:3478
      - TURN_SERVER_USER=misskey
      - TURN_SERVER_PASS=turnpassword
    restart: always

  turn_server:
    image: coturn/coturn:4.6
    volumes:
      - ./turn/turnserver.conf:/etc/coturn/turnserver.conf
    network_mode: "host"
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    sysctls:
      - net.core.somaxconn=1024
      - vm.overcommit_memory=1
    restart: always

volumes:
  redis_data: